use_frameworks!

platform :ios, '9.0'

target 'SafetyNotification_Example' do
  pod 'SafetyNotification', :path => '../'

  target 'SafetyNotification_Tests' do
    inherit! :search_paths

    
  end
end
